#ifndef CLAIRE_THREADING_TYPES_H
#define CLAIRE_THREADING_TYPES_H

#if CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_STD
#	include "Threading\STD\ClaireThreadingTypesSTD.h"
#elif CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_BOOST
#	include "Threading\Boost\ClaireThreadingTypesBoost.h"
#elif CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_POSIX
#	include ""
#elif CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_TBB
#	include ""
#endif

#endif