#ifndef CLAIRE_THREADING_INCLUDES_H
#define CLAIRE_THREADING_INCLUDES_H

#if CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_STD
#	include "Threading\STD\ClaireThreadingIncludesSTD.h"
#elif CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_BOOST
#	include "Threading\Boost\ClaireThreadingIncludesBoost.h"
#elif CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_POSIX
#	include ""
#elif CLAIRE_THREADING_PROVIDER == CLAIRE_THREADING_PROVIDER_TBB
#	include ""
#endif

#endif