#ifndef CLAIRE_BUILD_SETTINGS_H
#define CLAIRE_BUILD_SETTINGS_H

#define CLAIRE_DOUBLE_PRECISION 0
	
#define CLAIRE_CONTAINERS_USE_CUSTOM_MEMORY_ALLOCATOR 0
//#define CLAIRE_CONTAINERS_USE_CUSTOM_MEMORY_ALLOCATOR 1


#define CLAIRE_THREAD_SUPPORT 1

#include "ClaireThreadingProviders.h"

//#define CLAIRE_THREADING_PROVIDER CLAIRE_THREADING_PROVIDER_BOOST
#define CLAIRE_THREADING_PROVIDER CLAIRE_THREADING_PROVIDER_STD

#endif