#ifndef CLAIRE_THREADING_PROVIDERS_H
#define CLAIRE_THREADING_PROVIDERS_H

#define CLAIRE_THREADING_PROVIDER_STD 0
#define CLAIRE_THREADING_PROVIDER_BOOST 1
#define CLAIRE_THREADING_PROVIDER_POSIX 2
#define CLAIRE_THREADING_PROVIDER_TBB 3

#endif